export { default as Back } from '@material-ui/icons/ChevronLeftRounded';
export { default as FullResolution } from '@material-ui/icons/HighQualityRounded';
export { default as Functions } from '@material-ui/icons/FunctionsRounded'
export { default as Help } from '@material-ui/icons/HelpOutlineRounded';
export { default as Menu } from '@material-ui/icons/MenuRounded';
export { default as Minus } from '@material-ui/icons/RemoveCircleRounded';
export { default as Navigate } from '@material-ui/icons/ControlCameraRounded';
export { default as Palette } from '@material-ui/icons/PaletteRounded';
export { default as Plus } from '@material-ui/icons/AddCircleRounded';
export { default as Random } from '@material-ui/icons/CasinoRounded';
export { default as Recenter } from '@material-ui/icons/FilterCenterFocusRounded';
export { default as RotateLeft } from '@material-ui/icons/RotateLeftRounded';
export { default as RotateRight } from '@material-ui/icons/RotateRightRounded';
export { default as Settings } from '@material-ui/icons/SettingsRounded';
export { default as Tune } from '@material-ui/icons/TuneRounded';
//export { default as View } from '@material-ui/icons/PhotoSizeSelectLargeRounded';
export { default as View } from '@material-ui/icons/SettingsOverscanRounded';
export { default as ZoomIn } from '@material-ui/icons/ZoomInRounded';
export { default as ZoomOut } from '@material-ui/icons/ZoomOutRounded';